# Generated by Django 5.0.1 on 2024-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('USER', 'User')], default='USER', max_length=30),
        ),
    ]
