# Generated by Django 5.0.1 on 2024-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_category_remove_test_subject_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_answers',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
