# Generated by Django 5.0.1 on 2024-02-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_correct_answer_question_incorrect_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answers',
            new_name='choices',
        ),
    ]
